name: Build iOS App

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Enables manual triggering

jobs:
  build:
    runs-on: macos-latest  # macOS runner is required for Xcode builds

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Install dependencies
        run: |
          # Install any dependencies, e.g., CocoaPods, SPM, etc.
          # If using CocoaPods
          # pod install
          
      - name: Build iOS app
        run: |
          # Configure build settings
          APP_NAME="Asspp"
          WORKSPACE="${APP_NAME}.xcworkspace"
          SCHEME="${APP_NAME}"
          CONFIGURATION="Release"
          
          # Use xcworkspace if you have CocoaPods, otherwise use xcodeproj
          if [ -d "${WORKSPACE}" ]; then
            xcodebuild clean archive -workspace "${WORKSPACE}" -scheme "${SCHEME}" -configuration "${CONFIGURATION}" -archivePath "${APP_NAME}.xcarchive" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          else
            xcodebuild clean archive -project "${APP_NAME}.xcodeproj" -scheme "${SCHEME}" -configuration "${CONFIGURATION}" -archivePath "${APP_NAME}.xcarchive" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          fi
          
          # Create IPA from archive
          mkdir -p Payload
          cp -r "${APP_NAME}.xcarchive/Products/Applications/${APP_NAME}.app" Payload/
          zip -r "${APP_NAME}.ipa" Payload
          rm -rf Payload
        env:
          APP_NAME: Asspp

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: ${{ env.APP_NAME }}-ipa
          path: ${{ env.APP_NAME }}.ipa
          retention-days: 7
          
      # Optional: Create a GitHub release with the IPA file
      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            ${{ env.APP_NAME }}.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_NAME: Asspp